/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.interfaces;

import app.dbmanager.DBManager;
import app.pojos.User;
import java.awt.DefaultKeyboardFocusManager;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.util.List;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import sun.misc.BASE64Decoder;
import sun.misc.BASE64Encoder;

/**
 *
 * @author Sandaru
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    static int xx, yy;
    static Chat_ball chat_ball;
    int  id;

    public Login() {
        initComponents();

        Dimension screen_size = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(screen_size.width - 425, getY());

        //when app on
        signin_panel.setVisible(true);
        signup_panel.setVisible(false);
        forgot_password_panel.setVisible(false);
        chat_list_panel.setVisible(false);
        chat_area_panel.setVisible(false);
        setting_panel.setVisible(false);
        update_pwd_panel.setVisible(false);

        signin_default();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layered_pane = new javax.swing.JLayeredPane();
        title_panel = new javax.swing.JPanel();
        titlebar = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        signin_panel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        username_icon = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        username_line = new javax.swing.JLabel();
        password_icon = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        password_line = new javax.swing.JLabel();
        eye_open_icon = new javax.swing.JLabel();
        eye_close_icon = new javax.swing.JLabel();
        signin_btn = new javax.swing.JLabel();
        signin_error = new javax.swing.JLabel();
        forgot_password = new javax.swing.JTextField();
        forgot_password_hover = new javax.swing.JTextField();
        sign_up_link = new javax.swing.JTextField();
        sign_up_link_hover = new javax.swing.JTextField();
        signin_copyrights = new javax.swing.JLabel();
        signin_footer = new javax.swing.JLabel();
        signup_panel = new javax.swing.JPanel();
        signup_profile_pic = new javax.swing.JLabel();
        signup_email = new javax.swing.JTextField();
        signup_email_line = new javax.swing.JLabel();
        signup_username = new javax.swing.JTextField();
        signup_username_line = new javax.swing.JLabel();
        signup_password = new javax.swing.JPasswordField();
        signup_eye_open_icon = new javax.swing.JLabel();
        signup_eye_close_icon = new javax.swing.JLabel();
        signup_password_line = new javax.swing.JLabel();
        signup_nickname_line = new javax.swing.JLabel();
        signup_nickname = new javax.swing.JTextField();
        signup_btn = new javax.swing.JLabel();
        signup_error = new javax.swing.JLabel();
        signin_link = new javax.swing.JTextField();
        signin_link_hover = new javax.swing.JTextField();
        signup_copyrights = new javax.swing.JLabel();
        signup_footer = new javax.swing.JLabel();
        forgot_password_panel = new javax.swing.JPanel();
        fp_logo = new javax.swing.JLabel();
        fp_resend_code = new javax.swing.JLabel();
        fp_description = new javax.swing.JLabel();
        fp_recovery_code = new javax.swing.JTextField();
        fp_recovery_code_line = new javax.swing.JLabel();
        fp_confirm_btn = new javax.swing.JLabel();
        fp_error = new javax.swing.JLabel();
        fp_signin_link = new javax.swing.JTextField();
        fp_signin_link_hover = new javax.swing.JTextField();
        fp_copyrights = new javax.swing.JLabel();
        fp_footer = new javax.swing.JLabel();
        chat_list_panel = new javax.swing.JPanel();
        chatlist_title = new javax.swing.JLabel();
        chatlist_setting = new javax.swing.JLabel();
        users_name = new javax.swing.JLabel();
        username_lable = new javax.swing.JLabel();
        chatlist_item = new javax.swing.JPanel();
        chat_area_panel = new javax.swing.JPanel();
        signin_error1 = new javax.swing.JLabel();
        chatlist_title1 = new javax.swing.JLabel();
        chatlist_setting1 = new javax.swing.JLabel();
        setting_panel = new javax.swing.JPanel();
        setting_lable = new javax.swing.JLabel();
        setting_previous = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        update_pwd_panel = new javax.swing.JPanel();
        update_profile_pic = new javax.swing.JLabel();
        update_email = new javax.swing.JTextField();
        signup_email_line1 = new javax.swing.JLabel();
        update_username = new javax.swing.JTextField();
        signup_username_line1 = new javax.swing.JLabel();
        signup_nickname_line1 = new javax.swing.JLabel();
        update_nickname = new javax.swing.JTextField();
        success_msg = new javax.swing.JLabel();
        signin_link_hover1 = new javax.swing.JTextField();
        signup_copyrights1 = new javax.swing.JLabel();
        signup_footer1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        update_panel = new javax.swing.JPanel();
        update_profile_pic1 = new javax.swing.JLabel();
        update_email1 = new javax.swing.JTextField();
        signup_email_line2 = new javax.swing.JLabel();
        update_username1 = new javax.swing.JTextField();
        signup_username_line2 = new javax.swing.JLabel();
        signup_nickname_line2 = new javax.swing.JLabel();
        update_nickname1 = new javax.swing.JTextField();
        success_msg1 = new javax.swing.JLabel();
        signin_link_hover2 = new javax.swing.JTextField();
        signup_copyrights2 = new javax.swing.JLabel();
        signup_footer2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        layered_pane.setBackground(new java.awt.Color(28, 36, 47));

        title_panel.setBackground(new java.awt.Color(28, 36, 47));

        titlebar.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        titlebar.setForeground(new java.awt.Color(111, 117, 124));
        titlebar.setText("  Chat App");
        titlebar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titlebarMouseDragged(evt);
            }
        });
        titlebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titlebarMousePressed(evt);
            }
        });

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/minimize.png"))); // NOI18N
        minimize.setToolTipText("Minimize");
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/close.png"))); // NOI18N
        close.setToolTipText("Close");
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout title_panelLayout = new javax.swing.GroupLayout(title_panel);
        title_panel.setLayout(title_panelLayout);
        title_panelLayout.setHorizontalGroup(
            title_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title_panelLayout.createSequentialGroup()
                .addComponent(titlebar, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(minimize)
                .addGap(0, 0, 0)
                .addComponent(close)
                .addGap(0, 17, Short.MAX_VALUE))
        );
        title_panelLayout.setVerticalGroup(
            title_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, title_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(title_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titlebar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        signin_panel.setBackground(new java.awt.Color(28, 36, 47));
        signin_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/logo_pink.png"))); // NOI18N
        signin_panel.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 120, 120));

        username_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/username.png"))); // NOI18N
        signin_panel.add(username_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 20, 20));

        username.setBackground(new java.awt.Color(28, 36, 47));
        username.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N
        username.setForeground(new java.awt.Color(111, 117, 124));
        username.setText("sa");
        username.setAutoscrolls(false);
        username.setBorder(null);
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameMouseClicked(evt);
            }
        });
        signin_panel.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 240, 20));

        username_line.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/hrline.png"))); // NOI18N
        username_line.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        signin_panel.add(username_line, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, 10));

        password_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/password.png"))); // NOI18N
        signin_panel.add(password_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 20, 20));

        password.setBackground(new java.awt.Color(28, 36, 47));
        password.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N
        password.setForeground(new java.awt.Color(111, 117, 124));
        password.setText("123");
        password.setBorder(null);
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordMouseClicked(evt);
            }
        });
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        signin_panel.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 220, 20));

        password_line.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/hrline.png"))); // NOI18N
        password_line.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        signin_panel.add(password_line, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, 10));

        eye_open_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/eye_open.png"))); // NOI18N
        eye_open_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eye_open_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eye_open_iconMouseClicked(evt);
            }
        });
        signin_panel.add(eye_open_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 20, 20));

        eye_close_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/eye_close.png"))); // NOI18N
        eye_close_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eye_close_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eye_close_iconMouseClicked(evt);
            }
        });
        signin_panel.add(eye_close_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 20, 20));

        signin_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/signin_pink.png"))); // NOI18N
        signin_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signin_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signin_btnMouseClicked(evt);
            }
        });
        signin_panel.add(signin_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 200, 30));

        signin_error.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        signin_error.setForeground(new java.awt.Color(206, 47, 131));
        signin_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signin_panel.add(signin_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 310, -1));

        forgot_password.setEditable(false);
        forgot_password.setBackground(new java.awt.Color(28, 36, 47));
        forgot_password.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        forgot_password.setForeground(new java.awt.Color(111, 117, 124));
        forgot_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        forgot_password.setText("Forgot Password ?");
        forgot_password.setBorder(null);
        forgot_password.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgot_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                forgot_passwordMouseEntered(evt);
            }
        });
        signin_panel.add(forgot_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 110, 20));

        forgot_password_hover.setEditable(false);
        forgot_password_hover.setBackground(new java.awt.Color(28, 36, 47));
        forgot_password_hover.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        forgot_password_hover.setForeground(new java.awt.Color(206, 47, 131));
        forgot_password_hover.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        forgot_password_hover.setText("Forgot Password ?");
        forgot_password_hover.setBorder(null);
        forgot_password_hover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgot_password_hover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgot_password_hoverMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                forgot_password_hoverMouseExited(evt);
            }
        });
        forgot_password_hover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgot_password_hoverActionPerformed(evt);
            }
        });
        signin_panel.add(forgot_password_hover, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 110, 20));

        sign_up_link.setBackground(new java.awt.Color(28, 36, 47));
        sign_up_link.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        sign_up_link.setForeground(new java.awt.Color(111, 117, 124));
        sign_up_link.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sign_up_link.setText("Sign Up");
        sign_up_link.setBorder(null);
        sign_up_link.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sign_up_link.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sign_up_linkMouseEntered(evt);
            }
        });
        signin_panel.add(sign_up_link, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 50, 20));

        sign_up_link_hover.setEditable(false);
        sign_up_link_hover.setBackground(new java.awt.Color(28, 36, 47));
        sign_up_link_hover.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        sign_up_link_hover.setForeground(new java.awt.Color(206, 47, 131));
        sign_up_link_hover.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sign_up_link_hover.setText("Sign Up");
        sign_up_link_hover.setBorder(null);
        sign_up_link_hover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sign_up_link_hover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sign_up_link_hoverMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sign_up_link_hoverMouseExited(evt);
            }
        });
        signin_panel.add(sign_up_link_hover, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 50, 20));

        signin_copyrights.setFont(new java.awt.Font("Bookman Old Style", 0, 10)); // NOI18N
        signin_copyrights.setForeground(new java.awt.Color(255, 255, 255));
        signin_copyrights.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signin_copyrights.setText("<html><center>Copyrights &copy; 2020 Team Semicolon<br>All rights reserved</center></html>");
        signin_panel.add(signin_copyrights, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 360, 30));

        signin_footer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/footer.gif"))); // NOI18N
        signin_panel.add(signin_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 375, 130));

        signup_panel.setBackground(new java.awt.Color(28, 36, 47));
        signup_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signup_profile_pic.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        signup_profile_pic.setForeground(new java.awt.Color(111, 117, 124));
        signup_profile_pic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signup_profile_pic.setText("Profile Picture");
        signup_profile_pic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 117, 124), 2));
        signup_profile_pic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signup_profile_pic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signup_profile_picMouseClicked(evt);
            }
        });
        signup_panel.add(signup_profile_pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 120, 120));

        signup_email.setBackground(new java.awt.Color(28, 36, 47));
        signup_email.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N
        signup_email.setForeground(new java.awt.Color(111, 117, 124));
        signup_email.setText("Email");
        signup_email.setAutoscrolls(false);
        signup_email.setBorder(null);
        signup_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                signup_emailFocusLost(evt);
            }
        });
        signup_email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signup_emailMouseClicked(evt);
            }
        });
        signup_panel.add(signup_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 240, 20));

        signup_email_line.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/hrline.png"))); // NOI18N
        signup_email_line.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        signup_panel.add(signup_email_line, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, 10));

        signup_username.setBackground(new java.awt.Color(28, 36, 47));
        signup_username.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N
        signup_username.setForeground(new java.awt.Color(111, 117, 124));
        signup_username.setText("Username");
        signup_username.setAutoscrolls(false);
        signup_username.setBorder(null);
        signup_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                signup_usernameFocusLost(evt);
            }
        });
        signup_username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signup_usernameMouseClicked(evt);
            }
        });
        signup_panel.add(signup_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 240, 20));

        signup_username_line.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/hrline.png"))); // NOI18N
        signup_username_line.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        signup_panel.add(signup_username_line, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, 10));

        signup_password.setBackground(new java.awt.Color(28, 36, 47));
        signup_password.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N
        signup_password.setForeground(new java.awt.Color(111, 117, 124));
        signup_password.setText("Password");
        signup_password.setBorder(null);
        signup_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                signup_passwordFocusLost(evt);
            }
        });
        signup_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signup_passwordMouseClicked(evt);
            }
        });
        signup_panel.add(signup_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 220, 20));

        signup_eye_open_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/eye_open.png"))); // NOI18N
        signup_eye_open_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signup_eye_open_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signup_eye_open_iconMouseClicked(evt);
            }
        });
        signup_panel.add(signup_eye_open_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 20, 20));

        signup_eye_close_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/eye_close.png"))); // NOI18N
        signup_eye_close_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signup_eye_close_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signup_eye_close_iconMouseClicked(evt);
            }
        });
        signup_panel.add(signup_eye_close_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 20, 20));

        signup_password_line.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/hrline.png"))); // NOI18N
        signup_password_line.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        signup_panel.add(signup_password_line, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, 10));

        signup_nickname_line.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/hrline.png"))); // NOI18N
        signup_nickname_line.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        signup_panel.add(signup_nickname_line, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, 10));

        signup_nickname.setBackground(new java.awt.Color(28, 36, 47));
        signup_nickname.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N
        signup_nickname.setForeground(new java.awt.Color(111, 117, 124));
        signup_nickname.setText("Nick name");
        signup_nickname.setAutoscrolls(false);
        signup_nickname.setBorder(null);
        signup_nickname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                signup_nicknameFocusLost(evt);
            }
        });
        signup_nickname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signup_nicknameMouseClicked(evt);
            }
        });
        signup_panel.add(signup_nickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 240, 20));

        signup_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/signup_pink.png"))); // NOI18N
        signup_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signup_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signup_btnMouseClicked(evt);
            }
        });
        signup_panel.add(signup_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 200, 30));

        signup_error.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        signup_error.setForeground(new java.awt.Color(206, 47, 131));
        signup_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signup_panel.add(signup_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 310, 20));

        signin_link.setBackground(new java.awt.Color(28, 36, 47));
        signin_link.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        signin_link.setForeground(new java.awt.Color(111, 117, 124));
        signin_link.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        signin_link.setText("Sign In");
        signin_link.setBorder(null);
        signin_link.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signin_link.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signin_linkMouseEntered(evt);
            }
        });
        signin_link.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signin_linkActionPerformed(evt);
            }
        });
        signup_panel.add(signin_link, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 50, 20));

        signin_link_hover.setEditable(false);
        signin_link_hover.setBackground(new java.awt.Color(28, 36, 47));
        signin_link_hover.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        signin_link_hover.setForeground(new java.awt.Color(206, 47, 131));
        signin_link_hover.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        signin_link_hover.setText("Sign In");
        signin_link_hover.setBorder(null);
        signin_link_hover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signin_link_hover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signin_link_hoverMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signin_link_hoverMouseExited(evt);
            }
        });
        signup_panel.add(signin_link_hover, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 50, 20));

        signup_copyrights.setFont(new java.awt.Font("Bookman Old Style", 0, 10)); // NOI18N
        signup_copyrights.setForeground(new java.awt.Color(255, 255, 255));
        signup_copyrights.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signup_copyrights.setText("<html><center>Copyrights &copy; 2020 Team Semicolon<br>All rights reserved</center></html>");
        signup_panel.add(signup_copyrights, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 360, 30));

        signup_footer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/footer.gif"))); // NOI18N
        signup_panel.add(signup_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 375, 130));

        forgot_password_panel.setBackground(new java.awt.Color(28, 36, 47));
        forgot_password_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fp_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/logo_pink.png"))); // NOI18N
        forgot_password_panel.add(fp_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 120, 120));

        fp_resend_code.setFont(new java.awt.Font("Bookman Old Style", 1, 11)); // NOI18N
        fp_resend_code.setForeground(new java.awt.Color(206, 47, 131));
        fp_resend_code.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fp_resend_code.setText("resend code.");
        fp_resend_code.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgot_password_panel.add(fp_resend_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 80, -1));

        fp_description.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N
        fp_description.setForeground(new java.awt.Color(111, 117, 124));
        fp_description.setText("<html>We've sent a recovery code to your email.<br>Please enter the code to change your password. If you haven't received any mail, please</html>");
        forgot_password_panel.add(fp_description, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 240, 70));

        fp_recovery_code.setBackground(new java.awt.Color(28, 36, 47));
        fp_recovery_code.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N
        fp_recovery_code.setForeground(new java.awt.Color(111, 117, 124));
        fp_recovery_code.setText("Recovery code");
        fp_recovery_code.setAutoscrolls(false);
        fp_recovery_code.setBorder(null);
        fp_recovery_code.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fp_recovery_codeFocusLost(evt);
            }
        });
        fp_recovery_code.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fp_recovery_codeMouseClicked(evt);
            }
        });
        forgot_password_panel.add(fp_recovery_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 240, 20));

        fp_recovery_code_line.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/hrline.png"))); // NOI18N
        fp_recovery_code_line.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        forgot_password_panel.add(fp_recovery_code_line, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, 10));

        fp_confirm_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/confirm_pink.png"))); // NOI18N
        fp_confirm_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgot_password_panel.add(fp_confirm_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 200, 30));

        fp_error.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        fp_error.setForeground(new java.awt.Color(206, 47, 131));
        fp_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fp_error.setText("username and password are required");
        forgot_password_panel.add(fp_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 310, -1));

        fp_signin_link.setBackground(new java.awt.Color(28, 36, 47));
        fp_signin_link.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        fp_signin_link.setForeground(new java.awt.Color(111, 117, 124));
        fp_signin_link.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fp_signin_link.setText("Sign In");
        fp_signin_link.setBorder(null);
        fp_signin_link.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fp_signin_link.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fp_signin_linkMouseEntered(evt);
            }
        });
        forgot_password_panel.add(fp_signin_link, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 50, 20));

        fp_signin_link_hover.setEditable(false);
        fp_signin_link_hover.setBackground(new java.awt.Color(28, 36, 47));
        fp_signin_link_hover.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        fp_signin_link_hover.setForeground(new java.awt.Color(206, 47, 131));
        fp_signin_link_hover.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fp_signin_link_hover.setText("Sign In");
        fp_signin_link_hover.setBorder(null);
        fp_signin_link_hover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fp_signin_link_hover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fp_signin_link_hoverMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fp_signin_link_hoverMouseExited(evt);
            }
        });
        forgot_password_panel.add(fp_signin_link_hover, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 50, 20));

        fp_copyrights.setFont(new java.awt.Font("Bookman Old Style", 0, 10)); // NOI18N
        fp_copyrights.setForeground(new java.awt.Color(255, 255, 255));
        fp_copyrights.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fp_copyrights.setText("<html><center>Copyrights &copy; 2020 Team Semicolon<br>All rights reserved</center></html>");
        forgot_password_panel.add(fp_copyrights, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 360, 30));

        fp_footer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/footer.gif"))); // NOI18N
        forgot_password_panel.add(fp_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 375, 130));

        chat_list_panel.setBackground(new java.awt.Color(28, 36, 47));
        chat_list_panel.setPreferredSize(new java.awt.Dimension(375, 500));
        chat_list_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chatlist_title.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        chatlist_title.setForeground(new java.awt.Color(111, 117, 124));
        chatlist_title.setText("  Chats");
        chat_list_panel.add(chatlist_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 30));

        chatlist_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/setting_pink.png"))); // NOI18N
        chatlist_setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chatlist_settingMouseClicked(evt);
            }
        });
        chat_list_panel.add(chatlist_setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 30, 30));

        users_name.setBackground(new java.awt.Color(255, 255, 255));
        users_name.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        users_name.setForeground(new java.awt.Color(255, 255, 255));
        users_name.setText("Login success");
        chat_list_panel.add(users_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 120, 40));

        username_lable.setBackground(new java.awt.Color(255, 255, 255));
        username_lable.setForeground(new java.awt.Color(255, 255, 255));
        username_lable.setText("user");
        chat_list_panel.add(username_lable, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 66, 40, 30));

        chatlist_item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chatlist_itemMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout chatlist_itemLayout = new javax.swing.GroupLayout(chatlist_item);
        chatlist_item.setLayout(chatlist_itemLayout);
        chatlist_itemLayout.setHorizontalGroup(
            chatlist_itemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        chatlist_itemLayout.setVerticalGroup(
            chatlist_itemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        chat_list_panel.add(chatlist_item, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 350, 60));

        chat_area_panel.setBackground(new java.awt.Color(28, 36, 47));
        chat_area_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signin_error1.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        signin_error1.setForeground(new java.awt.Color(206, 47, 131));
        signin_error1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chat_area_panel.add(signin_error1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 310, -1));

        chatlist_title1.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        chatlist_title1.setForeground(new java.awt.Color(111, 117, 124));
        chatlist_title1.setText("  Chats");
        chat_area_panel.add(chatlist_title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 30));

        chatlist_setting1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/setting_pink.png"))); // NOI18N
        chatlist_setting1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chatlist_setting1MouseClicked(evt);
            }
        });
        chat_area_panel.add(chatlist_setting1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 30, 30));

        setting_panel.setBackground(new java.awt.Color(28, 36, 47));
        setting_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setting_lable.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        setting_lable.setForeground(new java.awt.Color(111, 117, 124));
        setting_lable.setText("  Setting");
        setting_panel.add(setting_lable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 30));

        setting_previous.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/setting_pink.png"))); // NOI18N
        setting_previous.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setting_previousMouseClicked(evt);
            }
        });
        setting_panel.add(setting_previous, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 30, 30));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Admin");
        setting_panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        update_pwd_panel.setBackground(new java.awt.Color(28, 36, 47));
        update_pwd_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        update_profile_pic.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        update_profile_pic.setForeground(new java.awt.Color(111, 117, 124));
        update_profile_pic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        update_profile_pic.setText("Profile Picture");
        update_profile_pic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 117, 124), 2));
        update_profile_pic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update_profile_pic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_profile_picMouseClicked(evt);
            }
        });
        update_pwd_panel.add(update_profile_pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 120, 120));

        update_email.setBackground(new java.awt.Color(28, 36, 47));
        update_email.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N
        update_email.setForeground(new java.awt.Color(111, 117, 124));
        update_email.setText("New Passowrd");
        update_email.setAutoscrolls(false);
        update_email.setBorder(null);
        update_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                update_emailFocusLost(evt);
            }
        });
        update_email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_emailMouseClicked(evt);
            }
        });
        update_pwd_panel.add(update_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 240, 20));

        signup_email_line1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/hrline.png"))); // NOI18N
        signup_email_line1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        update_pwd_panel.add(signup_email_line1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, 10));

        update_username.setBackground(new java.awt.Color(28, 36, 47));
        update_username.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N
        update_username.setForeground(new java.awt.Color(111, 117, 124));
        update_username.setText("New Corfirm Password");
        update_username.setAutoscrolls(false);
        update_username.setBorder(null);
        update_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                update_usernameFocusLost(evt);
            }
        });
        update_username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_usernameMouseClicked(evt);
            }
        });
        update_pwd_panel.add(update_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 240, 20));

        signup_username_line1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/hrline.png"))); // NOI18N
        signup_username_line1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        update_pwd_panel.add(signup_username_line1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, 10));

        signup_nickname_line1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/hrline.png"))); // NOI18N
        signup_nickname_line1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        update_pwd_panel.add(signup_nickname_line1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, 10));

        update_nickname.setBackground(new java.awt.Color(28, 36, 47));
        update_nickname.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N
        update_nickname.setForeground(new java.awt.Color(111, 117, 124));
        update_nickname.setText("Current Password");
        update_nickname.setAutoscrolls(false);
        update_nickname.setBorder(null);
        update_nickname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                update_nicknameFocusLost(evt);
            }
        });
        update_nickname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_nicknameMouseClicked(evt);
            }
        });
        update_pwd_panel.add(update_nickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 240, 20));

        success_msg.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        success_msg.setForeground(new java.awt.Color(206, 47, 131));
        success_msg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        update_pwd_panel.add(success_msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 280, -1));

        signin_link_hover1.setEditable(false);
        signin_link_hover1.setBackground(new java.awt.Color(28, 36, 47));
        signin_link_hover1.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        signin_link_hover1.setForeground(new java.awt.Color(206, 47, 131));
        signin_link_hover1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        signin_link_hover1.setText("Home");
        signin_link_hover1.setBorder(null);
        signin_link_hover1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signin_link_hover1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signin_link_hover1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signin_link_hover1MouseExited(evt);
            }
        });
        signin_link_hover1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signin_link_hover1ActionPerformed(evt);
            }
        });
        update_pwd_panel.add(signin_link_hover1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 50, 20));

        signup_copyrights1.setFont(new java.awt.Font("Bookman Old Style", 0, 10)); // NOI18N
        signup_copyrights1.setForeground(new java.awt.Color(255, 255, 255));
        signup_copyrights1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signup_copyrights1.setText("<html><center>Copyrights &copy; 2020 Team Semicolon<br>All rights reserved</center></html>");
        update_pwd_panel.add(signup_copyrights1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 360, 30));

        signup_footer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/footer.gif"))); // NOI18N
        update_pwd_panel.add(signup_footer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 375, 130));

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        update_pwd_panel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        update_panel.setBackground(new java.awt.Color(28, 36, 47));
        update_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        update_profile_pic1.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        update_profile_pic1.setForeground(new java.awt.Color(111, 117, 124));
        update_profile_pic1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        update_profile_pic1.setText("Profile Picture");
        update_profile_pic1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 117, 124), 2));
        update_profile_pic1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update_profile_pic1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_profile_pic1MouseClicked(evt);
            }
        });
        update_panel.add(update_profile_pic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 120, 120));

        update_email1.setBackground(new java.awt.Color(28, 36, 47));
        update_email1.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N
        update_email1.setForeground(new java.awt.Color(111, 117, 124));
        update_email1.setText("Email");
        update_email1.setAutoscrolls(false);
        update_email1.setBorder(null);
        update_email1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                update_email1FocusLost(evt);
            }
        });
        update_email1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_email1MouseClicked(evt);
            }
        });
        update_panel.add(update_email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 240, 20));

        signup_email_line2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/hrline.png"))); // NOI18N
        signup_email_line2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        update_panel.add(signup_email_line2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, 10));

        update_username1.setBackground(new java.awt.Color(28, 36, 47));
        update_username1.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N
        update_username1.setForeground(new java.awt.Color(111, 117, 124));
        update_username1.setText("Username");
        update_username1.setAutoscrolls(false);
        update_username1.setBorder(null);
        update_username1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                update_username1FocusLost(evt);
            }
        });
        update_username1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_username1MouseClicked(evt);
            }
        });
        update_panel.add(update_username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 240, 20));

        signup_username_line2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/hrline.png"))); // NOI18N
        signup_username_line2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        update_panel.add(signup_username_line2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, 10));

        signup_nickname_line2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/hrline.png"))); // NOI18N
        signup_nickname_line2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        update_panel.add(signup_nickname_line2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, 10));

        update_nickname1.setBackground(new java.awt.Color(28, 36, 47));
        update_nickname1.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N
        update_nickname1.setForeground(new java.awt.Color(111, 117, 124));
        update_nickname1.setText("Nick name");
        update_nickname1.setAutoscrolls(false);
        update_nickname1.setBorder(null);
        update_nickname1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                update_nickname1FocusLost(evt);
            }
        });
        update_nickname1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_nickname1MouseClicked(evt);
            }
        });
        update_panel.add(update_nickname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 240, 20));

        success_msg1.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        success_msg1.setForeground(new java.awt.Color(206, 47, 131));
        success_msg1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        update_panel.add(success_msg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 280, -1));

        signin_link_hover2.setEditable(false);
        signin_link_hover2.setBackground(new java.awt.Color(28, 36, 47));
        signin_link_hover2.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        signin_link_hover2.setForeground(new java.awt.Color(206, 47, 131));
        signin_link_hover2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        signin_link_hover2.setText("Home");
        signin_link_hover2.setBorder(null);
        signin_link_hover2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signin_link_hover2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signin_link_hover2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signin_link_hover2MouseExited(evt);
            }
        });
        signin_link_hover2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signin_link_hover2ActionPerformed(evt);
            }
        });
        update_panel.add(signin_link_hover2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 50, 20));

        signup_copyrights2.setFont(new java.awt.Font("Bookman Old Style", 0, 10)); // NOI18N
        signup_copyrights2.setForeground(new java.awt.Color(255, 255, 255));
        signup_copyrights2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signup_copyrights2.setText("<html><center>Copyrights &copy; 2020 Team Semicolon<br>All rights reserved</center></html>");
        update_panel.add(signup_copyrights2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 360, 30));

        signup_footer2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/footer.gif"))); // NOI18N
        update_panel.add(signup_footer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 375, 130));

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        update_panel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        layered_pane.setLayer(title_panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layered_pane.setLayer(signin_panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layered_pane.setLayer(signup_panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layered_pane.setLayer(forgot_password_panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layered_pane.setLayer(chat_list_panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layered_pane.setLayer(chat_area_panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layered_pane.setLayer(setting_panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layered_pane.setLayer(update_pwd_panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layered_pane.setLayer(update_panel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layered_paneLayout = new javax.swing.GroupLayout(layered_pane);
        layered_pane.setLayout(layered_paneLayout);
        layered_paneLayout.setHorizontalGroup(
            layered_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layered_paneLayout.createSequentialGroup()
                .addComponent(signin_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layered_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(signup_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layered_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(forgot_password_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layered_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(chat_list_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE))
            .addGroup(layered_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(setting_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE))
            .addGroup(layered_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layered_paneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(update_pwd_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layered_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layered_paneLayout.createSequentialGroup()
                    .addComponent(update_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 12, Short.MAX_VALUE)))
            .addGroup(layered_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layered_paneLayout.createSequentialGroup()
                    .addComponent(chat_area_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 14, Short.MAX_VALUE)))
        );
        layered_paneLayout.setVerticalGroup(
            layered_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layered_paneLayout.createSequentialGroup()
                .addComponent(title_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(signin_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layered_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layered_paneLayout.createSequentialGroup()
                    .addGap(0, 30, Short.MAX_VALUE)
                    .addComponent(signup_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layered_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layered_paneLayout.createSequentialGroup()
                    .addGap(0, 30, Short.MAX_VALUE)
                    .addComponent(forgot_password_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layered_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layered_paneLayout.createSequentialGroup()
                    .addGap(0, 30, Short.MAX_VALUE)
                    .addComponent(chat_list_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layered_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layered_paneLayout.createSequentialGroup()
                    .addGap(0, 34, Short.MAX_VALUE)
                    .addComponent(setting_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layered_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layered_paneLayout.createSequentialGroup()
                    .addContainerGap(24, Short.MAX_VALUE)
                    .addComponent(update_pwd_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layered_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layered_paneLayout.createSequentialGroup()
                    .addContainerGap(24, Short.MAX_VALUE)
                    .addComponent(update_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layered_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layered_paneLayout.createSequentialGroup()
                    .addContainerGap(26, Short.MAX_VALUE)
                    .addComponent(chat_area_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        getContentPane().add(layered_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 375, 525));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void forgot_password_hoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgot_password_hoverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_forgot_password_hoverActionPerformed

    private void forgot_passwordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgot_passwordMouseEntered
        forgot_password.setVisible(false);
        forgot_password_hover.setVisible(true);
    }//GEN-LAST:event_forgot_passwordMouseEntered

    private void forgot_password_hoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgot_password_hoverMouseExited
        forgot_password_hover.setVisible(false);
        forgot_password.setVisible(true);
    }//GEN-LAST:event_forgot_password_hoverMouseExited

    private void sign_up_linkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_up_linkMouseEntered
        sign_up_link.setVisible(false);
        sign_up_link_hover.setVisible(true);
    }//GEN-LAST:event_sign_up_linkMouseEntered

    private void sign_up_link_hoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_up_link_hoverMouseExited
        sign_up_link_hover.setVisible(false);
        sign_up_link.setVisible(true);
    }//GEN-LAST:event_sign_up_link_hoverMouseExited

    private void eye_open_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eye_open_iconMouseClicked
        if (password.getText().trim().equalsIgnoreCase("password")) {

        } else {
            eye_close_icon.setVisible(true);
            eye_open_icon.setVisible(false);
            password.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_eye_open_iconMouseClicked

    private void eye_close_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eye_close_iconMouseClicked
        if (password.getText().trim().equalsIgnoreCase("password")) {

        } else {
            eye_open_icon.setVisible(true);
            eye_close_icon.setVisible(false);
            password.setEchoChar('●');
        }
    }//GEN-LAST:event_eye_close_iconMouseClicked

    private void usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameMouseClicked
        if (username.getText().trim().equalsIgnoreCase("username")) {
            username.setText(null);
        }
    }//GEN-LAST:event_usernameMouseClicked

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        if (username.getText().trim().equalsIgnoreCase("")) {
            username.setText("Username");
        }
    }//GEN-LAST:event_usernameFocusLost

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        if (password.getText().trim().equalsIgnoreCase("")) {
            password.setText("Password");
            password.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_passwordFocusLost

    private void passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseClicked
        if (password.getText().trim().equalsIgnoreCase("password")) {
            password.setText(null);
            password.setEchoChar('●');
        }
    }//GEN-LAST:event_passwordMouseClicked

    private void signup_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signup_usernameFocusLost
        if (signup_username.getText().trim().equalsIgnoreCase("")) {
            signup_username.setText("Username");
        }
    }//GEN-LAST:event_signup_usernameFocusLost

    private void signup_usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signup_usernameMouseClicked
        if (signup_username.getText().trim().equalsIgnoreCase("username")) {
            signup_username.setText(null);
        }
    }//GEN-LAST:event_signup_usernameMouseClicked

    private void signup_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signup_passwordFocusLost
        if (signup_password.getText().trim().equalsIgnoreCase("")) {
            signup_password.setText("Password");
            signup_password.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_signup_passwordFocusLost

    private void signup_passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signup_passwordMouseClicked
        if (signup_password.getText().trim().equalsIgnoreCase("password")) {
            signup_password.setText(null);
            signup_password.setEchoChar('●');
        }
    }//GEN-LAST:event_signup_passwordMouseClicked

    private void signup_eye_open_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signup_eye_open_iconMouseClicked
        if (signup_password.getText().trim().equalsIgnoreCase("password")) {

        } else {
            signup_eye_close_icon.setVisible(true);
            signup_eye_open_icon.setVisible(false);
            signup_password.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_signup_eye_open_iconMouseClicked

    private void signup_eye_close_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signup_eye_close_iconMouseClicked
        if (signup_password.getText().trim().equalsIgnoreCase("password")) {

        } else {
            signup_eye_open_icon.setVisible(true);
            signup_eye_close_icon.setVisible(false);
            signup_password.setEchoChar('●');
        }
    }//GEN-LAST:event_signup_eye_close_iconMouseClicked

    private void signin_linkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signin_linkMouseEntered
        signin_link.setVisible(false);
        signin_link_hover.setVisible(true);
    }//GEN-LAST:event_signin_linkMouseEntered

    private void signin_link_hoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signin_link_hoverMouseExited
        signin_link_hover.setVisible(false);
        signin_link.setVisible(true);
    }//GEN-LAST:event_signin_link_hoverMouseExited

    private void signin_linkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signin_linkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signin_linkActionPerformed

    private void sign_up_link_hoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_up_link_hoverMouseClicked
        signup_default();
    }//GEN-LAST:event_sign_up_link_hoverMouseClicked

    private void signup_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signup_emailFocusLost
        if (signup_email.getText().trim().equalsIgnoreCase("")) {
            signup_email.setText("Email");
        }
    }//GEN-LAST:event_signup_emailFocusLost

    private void signup_emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signup_emailMouseClicked
        if (signup_email.getText().trim().equalsIgnoreCase("email")) {
            signup_email.setText(null);
        }
    }//GEN-LAST:event_signup_emailMouseClicked

    private void signup_nicknameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signup_nicknameFocusLost
        if (signup_nickname.getText().trim().equalsIgnoreCase("")) {
            signup_nickname.setText("Nick name");
        }
    }//GEN-LAST:event_signup_nicknameFocusLost

    private void signup_nicknameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signup_nicknameMouseClicked
        if (signup_nickname.getText().trim().equalsIgnoreCase("nick name")) {
            signup_nickname.setText(null);
        }
    }//GEN-LAST:event_signup_nicknameMouseClicked

    private void signin_link_hoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signin_link_hoverMouseClicked
        signin_default();
    }//GEN-LAST:event_signin_link_hoverMouseClicked

    private void signup_profile_picMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signup_profile_picMouseClicked
        JFileChooser chooser = new JFileChooser(); //open image file file
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG & PNG Images", "jpg", "png"); //set image type filter
        chooser.setFileFilter(filter); //filter
        int returnVal = chooser.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) { //if image selected
            File file = chooser.getSelectedFile(); //get selected file
            String strfilepath = file.getAbsolutePath(); //get abs path
//            System.out.println(strfilepath);
            try {
                ImageIcon icon = new ImageIcon(strfilepath); //string image path open as a image icon
                ImageIcon iconresized = new ImageIcon(icon.getImage().getScaledInstance(120, 120, Image.SCALE_DEFAULT)); //resize image icon fit for profile icon label
                signup_profile_pic.setText(null); // remove label text
                signup_profile_pic.setIcon(iconresized); //set seleted image to profile icon label 

//               String img = this.encodeToString(this.ImageIconToBufferedImage(iconresized),"jpg"); 
//               BufferedImage bimg = this.decodeToImage(img);
//               
//               signup_profile_pic.setIcon(new ImageIcon(bimg));
            } catch (Exception e) {
                System.out.println("Exception occurred : " + e.getMessage());
            }
        }
    }//GEN-LAST:event_signup_profile_picMouseClicked

    private void titlebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlebarMousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_titlebarMousePressed

    private void titlebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlebarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_titlebarMouseDragged

    private void fp_signin_linkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fp_signin_linkMouseEntered
        fp_signin_link.setVisible(false);
        fp_signin_link_hover.setVisible(true);
    }//GEN-LAST:event_fp_signin_linkMouseEntered

    private void fp_signin_link_hoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fp_signin_link_hoverMouseClicked
        signin_default();
    }//GEN-LAST:event_fp_signin_link_hoverMouseClicked

    private void fp_signin_link_hoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fp_signin_link_hoverMouseExited
        fp_signin_link_hover.setVisible(false);
        fp_signin_link.setVisible(true);
    }//GEN-LAST:event_fp_signin_link_hoverMouseExited

    private void fp_recovery_codeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fp_recovery_codeFocusLost
        if (fp_recovery_code.getText().trim().equalsIgnoreCase("")) {
            fp_recovery_code.setText("Recovery code");
        }
    }//GEN-LAST:event_fp_recovery_codeFocusLost

    private void fp_recovery_codeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fp_recovery_codeMouseClicked
        if (fp_recovery_code.getText().trim().equalsIgnoreCase("recovery code")) {
            fp_recovery_code.setText(null);
        }
    }//GEN-LAST:event_fp_recovery_codeMouseClicked

    private void forgot_password_hoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgot_password_hoverMouseClicked
        forgot_password_default();
    }//GEN-LAST:event_forgot_password_hoverMouseClicked

    private void update_profile_picMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_profile_picMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_update_profile_picMouseClicked

    private void update_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_update_emailFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_update_emailFocusLost

    private void update_emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_emailMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_update_emailMouseClicked

    private void update_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_update_usernameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_update_usernameFocusLost

    private void update_usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_usernameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_update_usernameMouseClicked

    private void update_nicknameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_update_nicknameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_update_nicknameFocusLost

    private void update_nicknameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_nicknameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_update_nicknameMouseClicked

    private void signin_link_hover1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signin_link_hover1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_signin_link_hover1MouseClicked

    private void signin_link_hover1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signin_link_hover1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_signin_link_hover1MouseExited

    private void signin_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signin_btnMouseClicked

        String user_name = username.getText();
        String user_pwd = password.getText();

//        if(user_name.equals(" ")){
        List data = DBManager.getDBM().login(user_name, user_pwd);
        Iterator i = data.iterator();
        if (i.hasNext()) {
            User user = (User) i.next();
            if (user.getId().equals(1)) {
                System.out.println(user.getUsername());
                setting_default();
//                update_email.setText(user.getEmail());
            } else {
                chat_list_default();
            }
            users_name.setText(user.getNickname());
            this.id=user.getId();
            update_nickname.setText(user.getNickname());
            update_email.setText(user.getEmail());
            update_username.setText(user.getUsername());
//           update_profile_pic.setText(user.getAvatar());

        } else {
            System.out.println("no user");
            signin_error.setText("Username or Password Incorrect");
        }
//        }else{
//            signin_error.setText("Username and Password Required");
//        }
    }//GEN-LAST:event_signin_btnMouseClicked

    private void signup_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signup_btnMouseClicked
        signup_default();

        //get data from text boxes
        String email = signup_email.getText();
        String username = signup_username.getText();
        String nickname = signup_nickname.getText();
        String password = signup_password.getText();

        //error array
        ArrayList<String> error = validateform(email, username, nickname, password);

        if (error.isEmpty() == false) {
            signup_error.setText(error.get(0));
        } else {
            signup_error.setText(null);
            //intsert details
            byte[] img = null;
            ImageIcon avatar = (ImageIcon) signup_profile_pic.getIcon();
            if (avatar != null) {
                try {
                    //                img = this.encodeToString(this.ImageIconToBufferedImage(avatar),"jpg");
                    BufferedImage bImage = ImageIconToBufferedImage(avatar);
                    ByteArrayOutputStream bos = new ByteArrayOutputStream();
                    ImageIO.write(bImage, "jpg", bos);
                    img = bos.toByteArray();

                } catch (IOException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

            DBManager.getDBM().insert(img, email, username, nickname, password);

        }


    }//GEN-LAST:event_signup_btnMouseClicked

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void setting_previousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setting_previousMouseClicked
        update_default();
    }//GEN-LAST:event_setting_previousMouseClicked

    private void chatlist_settingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatlist_settingMouseClicked
        update_default();
    }//GEN-LAST:event_chatlist_settingMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String email = update_email.getText().trim();
        String username = update_username.getText().trim();
        String nickname = update_nickname.getText().trim();
//        String password = update_password.getText().trim();
        byte[] update_img=null;
        
        DBManager.getDBM().update(update_img, email, username, nickname,id);
        success_msg.setText("success update!");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void signin_link_hover1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signin_link_hover1ActionPerformed
        chat_list_default();
        System.out.println("go to home");
    }//GEN-LAST:event_signin_link_hover1ActionPerformed

    private void update_profile_pic1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_profile_pic1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_update_profile_pic1MouseClicked

    private void update_email1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_update_email1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_update_email1FocusLost

    private void update_email1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_email1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_update_email1MouseClicked

    private void update_username1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_update_username1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_update_username1FocusLost

    private void update_username1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_username1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_update_username1MouseClicked

    private void update_nickname1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_update_nickname1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_update_nickname1FocusLost

    private void update_nickname1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_nickname1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_update_nickname1MouseClicked

    private void signin_link_hover2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signin_link_hover2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_signin_link_hover2MouseClicked

    private void signin_link_hover2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signin_link_hover2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_signin_link_hover2MouseExited

    private void signin_link_hover2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signin_link_hover2ActionPerformed
        System.out.println("vvghv");
    }//GEN-LAST:event_signin_link_hover2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void chatlist_itemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatlist_itemMouseClicked
        chatarea_default();
    }//GEN-LAST:event_chatlist_itemMouseClicked

    private void chatlist_setting1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatlist_setting1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_chatlist_setting1MouseClicked

    public void signin_default() {
        signin_panel.setVisible(true);
        signup_panel.setVisible(false);
        forgot_password_panel.setVisible(false);
        chat_list_panel.setVisible(false);
        chat_area_panel.setVisible(false);
        setting_panel.setVisible(false);
        update_pwd_panel.setVisible(false);
        update_panel.setVisible(false);

        password.setEchoChar((char) 0);
        eye_open_icon.setVisible(true);
        eye_close_icon.setVisible(false);
    }

    public void signup_default() {
        signin_panel.setVisible(false);
        signup_panel.setVisible(true);
        forgot_password_panel.setVisible(false);
        chat_list_panel.setVisible(false);
        chat_area_panel.setVisible(false);
        setting_panel.setVisible(false);
        update_pwd_panel.setVisible(false);
        update_panel.setVisible(false);

        signup_password.setEchoChar((char) 0);
        signup_eye_open_icon.setVisible(true);
        signup_eye_close_icon.setVisible(false);
    }

    public void forgot_password_default() {
        signin_panel.setVisible(false);
        signup_panel.setVisible(false);
        forgot_password_panel.setVisible(true);
        chat_list_panel.setVisible(false);
        chat_area_panel.setVisible(false);
        setting_panel.setVisible(false);
        update_pwd_panel.setVisible(false);
        update_panel.setVisible(false);
    }
    
    public void chang_password_default() {
        signin_panel.setVisible(false);
        signup_panel.setVisible(false);
        forgot_password_panel.setVisible(false);
        chat_list_panel.setVisible(false);
        chat_area_panel.setVisible(false);
        setting_panel.setVisible(false);
        update_pwd_panel.setVisible(false);
        update_panel.setVisible(true);
    }

    public void chat_list_default() {
        signin_panel.setVisible(false);
        signup_panel.setVisible(false);
        forgot_password_panel.setVisible(false);
        chat_list_panel.setVisible(true);
        chat_area_panel.setVisible(false);
        setting_panel.setVisible(false);
        update_pwd_panel.setVisible(false);
        update_panel.setVisible(false);
    }

    public void chat_area_default() {
        signin_panel.setVisible(false);
        signup_panel.setVisible(false);
        forgot_password_panel.setVisible(false);
        chat_list_panel.setVisible(false);
        chat_area_panel.setVisible(true);
        setting_panel.setVisible(false);
        update_pwd_panel.setVisible(false);
        update_panel.setVisible(false);
    }

    public void setting_default() {
        signin_panel.setVisible(false);
        signup_panel.setVisible(false);
        forgot_password_panel.setVisible(false);
        chat_list_panel.setVisible(false);
        chat_area_panel.setVisible(false);
        setting_panel.setVisible(true);
        update_pwd_panel.setVisible(false);
        update_panel.setVisible(false);
    }

    public void update_default() {
        signin_panel.setVisible(false);
        signup_panel.setVisible(false);
        forgot_password_panel.setVisible(false);
        chat_list_panel.setVisible(false);
        chat_area_panel.setVisible(false);
        setting_panel.setVisible(false);
        update_pwd_panel.setVisible(true);
        update_panel.setVisible(false);
    }
    
    public void chatlist_default() {
        signin_panel.setVisible(false);
        signup_panel.setVisible(false);
        forgot_password_panel.setVisible(false);
        chat_list_panel.setVisible(true);
        chat_area_panel.setVisible(false);
        setting_panel.setVisible(false);
        update_pwd_panel.setVisible(false);
        update_panel.setVisible(false);
    }
    
    public void chatarea_default() {
        signin_panel.setVisible(false);
        signup_panel.setVisible(false);
        forgot_password_panel.setVisible(false);
        chat_list_panel.setVisible(false);
        chat_area_panel.setVisible(true);
        setting_panel.setVisible(false);
        update_pwd_panel.setVisible(false);
        update_panel.setVisible(false);
    }

    public ArrayList<String> validateform(String email, String username, String nickname, String password) {

        ArrayList<String> errors = new ArrayList<String>();

        if (email.matches("^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$") == false) {
            errors.add("Invalid email");
        }

        if ("Username".equals(username) || "".equals(username)) {
            errors.add("Username is requird");
        }

        if ("Password".equals(password) || "".equals(password)) {
            errors.add("Password is requird");
        }

        if (password.length() < 7) {
            errors.add("Password must contain more than 8 characters");
        }

        if ("Nick name".equals(nickname) || "".equals(nickname)) {
            errors.add("Nickname is requird");
        }

        return errors;
    }

    public BufferedImage ImageIconToBufferedImage(ImageIcon icon) {
        BufferedImage bi = new BufferedImage(
                icon.getIconWidth(),
                icon.getIconHeight(),
                BufferedImage.TYPE_INT_RGB);
        Graphics g = bi.createGraphics();
        // paint the Icon to the BufferedImage.
        icon.paintIcon(null, g, 0, 0);
        g.dispose();

        return bi;
    }

//    public static String encodeToString(BufferedImage image, String type) {
//        String imageString = null;
//        ByteArrayOutputStream bos = new ByteArrayOutputStream();
//
//        try {
//            ImageIO.write(image, type, bos);
//            byte[] imageBytes = bos.toByteArray();
//
//            BASE64Encoder encoder = new BASE64Encoder();
//            imageString = encoder.encode(imageBytes);
//
//            bos.close();
//        } catch (IOException e) {
//
//        }
//        return imageString;
//    }

//    public static BufferedImage decodeToImage(String imageString) {
//
//        BufferedImage image = null;
//        byte[] imageByte;
//        try {
//            BASE64Decoder decoder = new BASE64Decoder();
//            imageByte = decoder.decodeBuffer(imageString);
//            ByteArrayInputStream bis = new ByteArrayInputStream(imageByte);
//            image = ImageIO.read(bis);
//            bis.close();
//        } catch (Exception e) {
//
//        }
//        return image;
//    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel chat_area_panel;
    private javax.swing.JPanel chat_list_panel;
    private javax.swing.JPanel chatlist_item;
    private javax.swing.JLabel chatlist_setting;
    private javax.swing.JLabel chatlist_setting1;
    private javax.swing.JLabel chatlist_title;
    private javax.swing.JLabel chatlist_title1;
    private javax.swing.JLabel close;
    private javax.swing.JLabel eye_close_icon;
    private javax.swing.JLabel eye_open_icon;
    private javax.swing.JTextField forgot_password;
    private javax.swing.JTextField forgot_password_hover;
    private javax.swing.JPanel forgot_password_panel;
    private javax.swing.JLabel fp_confirm_btn;
    private javax.swing.JLabel fp_copyrights;
    private javax.swing.JLabel fp_description;
    private javax.swing.JLabel fp_error;
    private javax.swing.JLabel fp_footer;
    private javax.swing.JLabel fp_logo;
    private javax.swing.JTextField fp_recovery_code;
    private javax.swing.JLabel fp_recovery_code_line;
    private javax.swing.JLabel fp_resend_code;
    private javax.swing.JTextField fp_signin_link;
    private javax.swing.JTextField fp_signin_link_hover;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLayeredPane layered_pane;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel minimize;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel password_icon;
    private javax.swing.JLabel password_line;
    private javax.swing.JLabel setting_lable;
    private javax.swing.JPanel setting_panel;
    private javax.swing.JLabel setting_previous;
    private javax.swing.JTextField sign_up_link;
    private javax.swing.JTextField sign_up_link_hover;
    private javax.swing.JLabel signin_btn;
    private javax.swing.JLabel signin_copyrights;
    private javax.swing.JLabel signin_error;
    private javax.swing.JLabel signin_error1;
    private javax.swing.JLabel signin_footer;
    private javax.swing.JTextField signin_link;
    private javax.swing.JTextField signin_link_hover;
    private javax.swing.JTextField signin_link_hover1;
    private javax.swing.JTextField signin_link_hover2;
    private javax.swing.JPanel signin_panel;
    private javax.swing.JLabel signup_btn;
    private javax.swing.JLabel signup_copyrights;
    private javax.swing.JLabel signup_copyrights1;
    private javax.swing.JLabel signup_copyrights2;
    private javax.swing.JTextField signup_email;
    private javax.swing.JLabel signup_email_line;
    private javax.swing.JLabel signup_email_line1;
    private javax.swing.JLabel signup_email_line2;
    private javax.swing.JLabel signup_error;
    private javax.swing.JLabel signup_eye_close_icon;
    private javax.swing.JLabel signup_eye_open_icon;
    private javax.swing.JLabel signup_footer;
    private javax.swing.JLabel signup_footer1;
    private javax.swing.JLabel signup_footer2;
    private javax.swing.JTextField signup_nickname;
    private javax.swing.JLabel signup_nickname_line;
    private javax.swing.JLabel signup_nickname_line1;
    private javax.swing.JLabel signup_nickname_line2;
    private javax.swing.JPanel signup_panel;
    private javax.swing.JPasswordField signup_password;
    private javax.swing.JLabel signup_password_line;
    private javax.swing.JLabel signup_profile_pic;
    private javax.swing.JTextField signup_username;
    private javax.swing.JLabel signup_username_line;
    private javax.swing.JLabel signup_username_line1;
    private javax.swing.JLabel signup_username_line2;
    private javax.swing.JLabel success_msg;
    private javax.swing.JLabel success_msg1;
    private javax.swing.JPanel title_panel;
    private javax.swing.JLabel titlebar;
    private javax.swing.JTextField update_email;
    private javax.swing.JTextField update_email1;
    private javax.swing.JTextField update_nickname;
    private javax.swing.JTextField update_nickname1;
    private javax.swing.JPanel update_panel;
    private javax.swing.JLabel update_profile_pic;
    private javax.swing.JLabel update_profile_pic1;
    private javax.swing.JPanel update_pwd_panel;
    private javax.swing.JTextField update_username;
    private javax.swing.JTextField update_username1;
    private javax.swing.JTextField username;
    private javax.swing.JLabel username_icon;
    private javax.swing.JLabel username_lable;
    private javax.swing.JLabel username_line;
    private javax.swing.JLabel users_name;
    // End of variables declaration//GEN-END:variables
}
