/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.interfaces;

/**
 *
 * @author Sandaru
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layered_pane = new javax.swing.JLayeredPane();
        signin_panel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        username_icon = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        username_line = new javax.swing.JLabel();
        password_icon = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        password_line = new javax.swing.JLabel();
        eye_open_icon = new javax.swing.JLabel();
        eye_close_icon = new javax.swing.JLabel();
        signin_btn = new javax.swing.JLabel();
        signin_error = new javax.swing.JLabel();
        forgot_password = new javax.swing.JTextField();
        forgot_password_hover = new javax.swing.JTextField();
        sign_up_link = new javax.swing.JTextField();
        sign_up_link_hover = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        signin_footer = new javax.swing.JLabel();
        signup_panel = new javax.swing.JPanel();
        title_panel = new javax.swing.JPanel();
        titlebar = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        close = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        layered_pane.setBackground(new java.awt.Color(28, 36, 47));

        signin_panel.setBackground(new java.awt.Color(28, 36, 47));
        signin_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/logo_pink.png"))); // NOI18N
        signin_panel.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 120, 120));

        username_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/username.png"))); // NOI18N
        signin_panel.add(username_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 20, 20));

        username.setBackground(new java.awt.Color(28, 36, 47));
        username.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N
        username.setForeground(new java.awt.Color(111, 117, 124));
        username.setText("Username");
        username.setAutoscrolls(false);
        username.setBorder(null);
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameMouseClicked(evt);
            }
        });
        signin_panel.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 240, 20));

        username_line.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/hrline.png"))); // NOI18N
        username_line.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        signin_panel.add(username_line, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, 10));

        password_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/password.png"))); // NOI18N
        signin_panel.add(password_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 20, 20));

        password.setBackground(new java.awt.Color(28, 36, 47));
        password.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N
        password.setForeground(new java.awt.Color(111, 117, 124));
        password.setText("Password");
        password.setBorder(null);
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordMouseClicked(evt);
            }
        });
        signin_panel.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 220, 20));

        password_line.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/hrline.png"))); // NOI18N
        password_line.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        signin_panel.add(password_line, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, 10));

        eye_open_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/eye_open.png"))); // NOI18N
        eye_open_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eye_open_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eye_open_iconMouseClicked(evt);
            }
        });
        signin_panel.add(eye_open_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 20, 20));

        eye_close_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/eye_close.png"))); // NOI18N
        eye_close_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eye_close_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eye_close_iconMouseClicked(evt);
            }
        });
        signin_panel.add(eye_close_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 20, 20));

        signin_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/signin_pink.png"))); // NOI18N
        signin_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signin_panel.add(signin_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 200, 30));

        signin_error.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        signin_error.setForeground(new java.awt.Color(206, 47, 131));
        signin_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signin_error.setText("username and password are required");
        signin_panel.add(signin_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 310, -1));

        forgot_password.setEditable(false);
        forgot_password.setBackground(new java.awt.Color(28, 36, 47));
        forgot_password.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        forgot_password.setForeground(new java.awt.Color(111, 117, 124));
        forgot_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        forgot_password.setText("Forgot Password ?");
        forgot_password.setBorder(null);
        forgot_password.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgot_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                forgot_passwordMouseEntered(evt);
            }
        });
        signin_panel.add(forgot_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 110, 20));

        forgot_password_hover.setEditable(false);
        forgot_password_hover.setBackground(new java.awt.Color(28, 36, 47));
        forgot_password_hover.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        forgot_password_hover.setForeground(new java.awt.Color(206, 47, 131));
        forgot_password_hover.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        forgot_password_hover.setText("Forgot Password ?");
        forgot_password_hover.setBorder(null);
        forgot_password_hover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgot_password_hover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                forgot_password_hoverMouseExited(evt);
            }
        });
        forgot_password_hover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgot_password_hoverActionPerformed(evt);
            }
        });
        signin_panel.add(forgot_password_hover, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 110, 20));

        sign_up_link.setBackground(new java.awt.Color(28, 36, 47));
        sign_up_link.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        sign_up_link.setForeground(new java.awt.Color(111, 117, 124));
        sign_up_link.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sign_up_link.setText("Sign Up");
        sign_up_link.setBorder(null);
        sign_up_link.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sign_up_link.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sign_up_linkMouseEntered(evt);
            }
        });
        signin_panel.add(sign_up_link, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 50, 20));

        sign_up_link_hover.setBackground(new java.awt.Color(28, 36, 47));
        sign_up_link_hover.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        sign_up_link_hover.setForeground(new java.awt.Color(206, 47, 131));
        sign_up_link_hover.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sign_up_link_hover.setText("Sign Up");
        sign_up_link_hover.setBorder(null);
        sign_up_link_hover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sign_up_link_hover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sign_up_link_hoverMouseExited(evt);
            }
        });
        signin_panel.add(sign_up_link_hover, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 50, 20));

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html><center>Copyrights &copy; 2020 Team Semicolon<br>All rights reserved</center></html>");
        signin_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 360, 30));

        signin_footer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/footer.gif"))); // NOI18N
        signin_panel.add(signin_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 375, 130));

        signup_panel.setBackground(new java.awt.Color(28, 36, 47));
        signup_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title_panel.setBackground(new java.awt.Color(28, 36, 47));

        titlebar.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        titlebar.setForeground(new java.awt.Color(111, 117, 124));
        titlebar.setText("  Chat App");
        titlebar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/minimize.png"))); // NOI18N
        minimize.setToolTipText("Minimize");
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/close.png"))); // NOI18N
        close.setToolTipText("Close");
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout title_panelLayout = new javax.swing.GroupLayout(title_panel);
        title_panel.setLayout(title_panelLayout);
        title_panelLayout.setHorizontalGroup(
            title_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title_panelLayout.createSequentialGroup()
                .addComponent(titlebar, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(minimize)
                .addComponent(close)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        title_panelLayout.setVerticalGroup(
            title_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, title_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(title_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titlebar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        layered_pane.setLayer(signin_panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layered_pane.setLayer(signup_panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layered_pane.setLayer(title_panel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layered_paneLayout = new javax.swing.GroupLayout(layered_pane);
        layered_pane.setLayout(layered_paneLayout);
        layered_paneLayout.setHorizontalGroup(
            layered_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signin_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(title_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layered_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(signup_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE))
        );
        layered_paneLayout.setVerticalGroup(
            layered_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layered_paneLayout.createSequentialGroup()
                .addComponent(title_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(signin_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layered_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layered_paneLayout.createSequentialGroup()
                    .addGap(0, 30, Short.MAX_VALUE)
                    .addComponent(signup_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(layered_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 375, 525));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void forgot_password_hoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgot_password_hoverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_forgot_password_hoverActionPerformed

    private void forgot_passwordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgot_passwordMouseEntered
        forgot_password.setVisible(false);
        forgot_password_hover.setVisible(true);
    }//GEN-LAST:event_forgot_passwordMouseEntered

    private void forgot_password_hoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgot_password_hoverMouseExited
        forgot_password_hover.setVisible(false);
        forgot_password.setVisible(true);
    }//GEN-LAST:event_forgot_password_hoverMouseExited

    private void sign_up_linkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_up_linkMouseEntered
        sign_up_link.setVisible(false);
        sign_up_link_hover.setVisible(true);
    }//GEN-LAST:event_sign_up_linkMouseEntered

    private void sign_up_link_hoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_up_link_hoverMouseExited
        sign_up_link_hover.setVisible(false);
        sign_up_link.setVisible(true);
    }//GEN-LAST:event_sign_up_link_hoverMouseExited

    private void eye_open_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eye_open_iconMouseClicked
        eye_close_icon.setVisible(true);
        eye_open_icon.setVisible(false);
        password.setEchoChar((char)0);
    }//GEN-LAST:event_eye_open_iconMouseClicked

    private void eye_close_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eye_close_iconMouseClicked
        eye_open_icon.setVisible(true);
        eye_close_icon.setVisible(false);
        password.setEchoChar('●');
    }//GEN-LAST:event_eye_close_iconMouseClicked

    private void usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameMouseClicked
        if (username.getText().trim().equalsIgnoreCase("username")) {
            username.setText(null);
        }
    }//GEN-LAST:event_usernameMouseClicked

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        if (username.getText().trim().equalsIgnoreCase("")) {
            username.setText("Username");
        }
    }//GEN-LAST:event_usernameFocusLost

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        if (password.getText().trim().equalsIgnoreCase("")) {
            password.setText("Password");
        }
    }//GEN-LAST:event_passwordFocusLost

    private void passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseClicked
        if (password.getText().trim().equalsIgnoreCase("password")) {
            password.setText(null);
        }
    }//GEN-LAST:event_passwordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close;
    private javax.swing.JLabel eye_close_icon;
    private javax.swing.JLabel eye_open_icon;
    private javax.swing.JTextField forgot_password;
    private javax.swing.JTextField forgot_password_hover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane layered_pane;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel minimize;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel password_icon;
    private javax.swing.JLabel password_line;
    private javax.swing.JTextField sign_up_link;
    private javax.swing.JTextField sign_up_link_hover;
    private javax.swing.JLabel signin_btn;
    private javax.swing.JLabel signin_error;
    private javax.swing.JLabel signin_footer;
    private javax.swing.JPanel signin_panel;
    private javax.swing.JPanel signup_panel;
    private javax.swing.JPanel title_panel;
    private javax.swing.JLabel titlebar;
    private javax.swing.JTextField username;
    private javax.swing.JLabel username_icon;
    private javax.swing.JLabel username_line;
    // End of variables declaration//GEN-END:variables
}
