package app.pojos;
// Generated Dec 19, 2020 11:28:01 PM by Hibernate Tools 4.3.1



/**
 * Files generated by hbm2java
 */
public class Files  implements java.io.Serializable {


     private Integer id;
     private int chatId;
     private int link;
     private boolean isDeleted;

    public Files() {
    }

    public Files(int chatId, int link, boolean isDeleted) {
       this.chatId = chatId;
       this.link = link;
       this.isDeleted = isDeleted;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getChatId() {
        return this.chatId;
    }
    
    public void setChatId(int chatId) {
        this.chatId = chatId;
    }
    public int getLink() {
        return this.link;
    }
    
    public void setLink(int link) {
        this.link = link;
    }
    public boolean isIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }




}


