package app.pojos;
// Generated Dec 18, 2020 5:10:53 PM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String nickname;
     private String email;
     private String avatar;
     private int isDeleted;
     private String password;

    public User() {
    }

	
    public User(String username, String nickname, String email, int isDeleted, String password) {
        this.username = username;
        this.nickname = nickname;
        this.email = email;
        this.isDeleted = isDeleted;
        this.password = password;
    }
    public User(String username, String nickname, String email, String avatar, int isDeleted, String password) {
       this.username = username;
       this.nickname = nickname;
       this.email = email;
       this.avatar = avatar;
       this.isDeleted = isDeleted;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getNickname() {
        return this.nickname;
    }
    
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAvatar() {
        return this.avatar;
    }
    
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


